island1:
    pos1:
        x: 0
        y: 0
        z: 0
    pos2:
        x: 0
        y: 0
        z: 0
        
island2:
    pos1:
        x: 0
        y: 0
        z: 0
    pos2:
        x: 0
        y: 0
        z: 0
          
lobby:
    pos1:
        x: 0
        y: 0
        z: 0
    pos2:
        x: 0
        y: 0
        z: 0

lobbyPortal:
    pos1:
        x: 0
        y: 0
        z: 0
    pos2:
        x: 0
        y: 0
        z: 0
        
lobbySpawn: 

Que1: 

Que2: 

islandSpawn1: 

islandSpawn2: 

setupMode: true

lobbyColor: GRAY

spectatorColor: DARK_BLUE

island1Color: ORANGE

island2Color: CYAN

portalList: 

