name: TNTWars
main: me.TNTWars.Raster556.TNTWars
version: 1.2
api-version: 1.13
commands:
    selectorTool:
        discription: Gives selection tool for defining regions
        usage: Syntax error! Perhaps you meant /<command>
    setIsland:
        discription: Sets the island region
        usage: Syntax error! Perhaps you meant /<command> <island int>
    setLobby:
        discription: Sets the lobby region
        usage: Syntax error! Perhaps you meant /<command>
    createPortal:
        discription: Creates the portal regions for game
        usage: Syntax error! Perhaps you meant /<command> <island int> <portal int>
    deletePortal:
        discription: Removes the portal regions for game
        usage: Syntax error! Perhaps you meant /<command> <island int> <portal int>
    setLobbyPortal:
        discription: Sets the portal region for lobby
        usage: Syntax error! Perhaps you meant /<command>
    setLobbySpawn:
        discription: Sets the lobby spawn
        usage: Syntax error! Perhaps you meant /<command>
    setQueSpawn:
        discription: Sets the que spawn
        usage: Syntax error! Perhaps you meant /<command> <que int>
    setIslandSpawn:
        discription: Sets the island spawn
        usage: Syntax error! Perhaps you meant /<command> <island int>
    setSetupMode:
        discription: Toggles setup mode
        usage: Syntax error! Perhaps you meant /<command> <state bool>
    lobby:
        discription: Go to lobby
        usage: Syntax error! Perhaps you meant /<command> 
    spectate:
        discription: Toggle spectating
        usage: Syntax error! Perhaps you meant /<command> 
    endGame:
        discription: Force end the game
        usage: Syntax error! Perhaps you meant /<command> 